// Context switch content removed — cleaned up as part of canonical exercise consolidation.
// This file remained for historical reasons; its content is no longer used.

export {};

    {
      id: "en-1",
      targetWord: "spark",
      contexts: [
        { name: "Romantic", hint: "Describe feelings or attraction" },
        { name: "Scientific", hint: "Use in a technical/physics context" },
        { name: "Professional", hint: "Use in a business/career context" },
      ],
      exampleAnswers: {
        Romantic: "There was an instant spark between them at the party.",
        Scientific: "The spark generated by the electrode ignited the gas mixture.",
        Professional: "Her presentation sparked a new direction for the project.",
      },
    },
    {
      id: "en-2",
      targetWord: "bridge",
      contexts: [
        { name: "Romantic", hint: "Describe connection or reconciliation" },
        { name: "Professional", hint: "Use in teamwork or networking" },
        { name: "Humorous", hint: "Make it funny or unexpected" },
      ],
      exampleAnswers: {
        Romantic: "Their late-night conversation bridged the gap that had grown between them.",
        Professional: "We need to bridge the communication gap between departments.",
        Humorous: "I tried to bridge the gap in my pants, but the button had other plans.",
      },
    },
    {
      id: "en-3",
      targetWord: "flame",
      contexts: [
        { name: "Romantic", hint: "Describe passion or love" },
        { name: "Scientific", hint: "Use in chemistry or physics" },
        { name: "Professional", hint: "Use metaphorically in business" },
      ],
      exampleAnswers: {
        Romantic: "She was his old flame from college, and seeing her reignited forgotten feelings.",
        Scientific: "The flame test revealed the presence of copper ions in the solution.",
        Professional: "We need to fan the flame of innovation in our team.",
      },
    },
    {
      id: "en-4",
      targetWord: "current",
      contexts: [
        { name: "Scientific", hint: "Use in electricity or oceanography" },
        { name: "Professional", hint: "Use about trends or status" },
        { name: "Humorous", hint: "Play with the word's multiple meanings" },
      ],
      exampleAnswers: {
        Scientific: "The ocean current carried the debris hundreds of miles from shore.",
        Professional: "Our current strategy isn't yielding the expected results.",
        Humorous: "I'm not current on the news because my electricity got cut off.",
      },
    },
    {
      id: "en-5",
      targetWord: "bloom",
      contexts: [
        { name: "Romantic", hint: "Describe love or beauty" },
        { name: "Scientific", hint: "Use in biology or ecology" },
        { name: "Professional", hint: "Use about growth or success" },
      ],
      exampleAnswers: {
        Romantic: "Their love bloomed slowly, like a flower opening to the sun.",
        Scientific: "The algal bloom in the lake depleted oxygen levels significantly.",
        Professional: "Her career really started to bloom after the promotion.",
      },
    },
    {
      id: "en-6",
      targetWord: "wave",
      contexts: [
        { name: "Casual", hint: "Social greeting" },
        { name: "Scientific", hint: "Physics or ocean context" },
        { name: "Professional", hint: "Business trends" },
      ],
      exampleAnswers: {
        Casual: "She gave a friendly wave from across the street.",
        Scientific: "The electromagnetic wave traveled at the speed of light.",
        Professional: "We're riding the wave of digital transformation.",
      },
    },
    {
      id: "en-7",
      targetWord: "charge",
      contexts: [
        { name: "Military", hint: "Attack or advance" },
        { name: "Financial", hint: "Cost or payment" },
        { name: "Scientific", hint: "Electricity or physics" },
      ],
      exampleAnswers: {
        Military: "The cavalry made a dramatic charge across the battlefield.",
        Financial: "There's no charge for the first month of service.",
        Scientific: "The electron carries a negative charge.",
      },
    },
    {
      id: "en-8",
      targetWord: "pitch",
      contexts: [
        { name: "Musical", hint: "Sound or tone" },
        { name: "Business", hint: "Presentation or proposal" },
        { name: "Sports", hint: "Baseball or cricket" },
      ],
      exampleAnswers: {
        Musical: "She has perfect pitch and can identify any note.",
        Business: "His pitch to the investors secured the funding they needed.",
        Sports: "The pitcher threw a fastball right down the middle.",
      },
    },
    {
      id: "en-9",
      targetWord: "drive",
      contexts: [
        { name: "Transportation", hint: "Operating a vehicle" },
        { name: "Psychological", hint: "Motivation or ambition" },
        { name: "Technology", hint: "Computer storage" },
      ],
      exampleAnswers: {
        Transportation: "It's a three-hour drive to the coast.",
        Psychological: "Her drive to succeed pushed her past every obstacle.",
        Technology: "Save the files to the cloud drive for backup.",
      },
    },
    {
      id: "en-10",
      targetWord: "scale",
      contexts: [
        { name: "Musical", hint: "Notes in sequence" },
        { name: "Business", hint: "Growth or size" },
        { name: "Scientific", hint: "Measurement or comparison" },
      ],
      exampleAnswers: {
        Musical: "She practiced the C major scale every morning.",
        Business: "We need to scale the operation to meet demand.",
        Scientific: "On a scale of 1 to 10, how would you rate your pain?",
      },
    },
    {
      id: "en-11",
      targetWord: "key",
      contexts: [
        { name: "Musical", hint: "Tonal center" },
        { name: "Problem-solving", hint: "Essential element" },
        { name: "Security", hint: "Access or lock" },
      ],
      exampleAnswers: {
        Musical: "The symphony was composed in the key of D minor.",
        "Problem-solving": "Communication is key to any successful relationship.",
        Security: "She lost the key to her apartment.",
      },
    },
    {
      id: "en-12",
      targetWord: "root",
      contexts: [
        { name: "Botanical", hint: "Plant structure" },
        { name: "Mathematical", hint: "Square root or origin" },
        { name: "Emotional", hint: "Origin or foundation" },
      ],
      exampleAnswers: {
        Botanical: "The root system of the oak tree spread across the entire yard.",
        Mathematical: "The square root of 144 is 12.",
        Emotional: "We need to get to the root of this problem.",
      },
    },
  ],
  fr: [
    {
      id: "fr-1",
      targetWord: "étincelle",
      contexts: [
        { name: "Romantique", hint: "Décrivez des sentiments ou une attirance" },
        { name: "Scientifique", hint: "Utilisez dans un contexte technique/physique" },
        { name: "Professionnel", hint: "Utilisez dans un contexte d'affaires" },
      ],
      exampleAnswers: {
        Romantique: "Il y avait une étincelle immédiate entre eux à la fête.",
        Scientifique: "L'étincelle générée par l'électrode a enflammé le mélange gazeux.",
        Professionnel: "Sa présentation a fait naître une étincelle de créativité dans l'équipe.",
      },
    },
    {
      id: "fr-2",
      targetWord: "pont",
      contexts: [
        { name: "Relationnel", hint: "Décrivez une connexion ou réconciliation" },
        { name: "Professionnel", hint: "Utilisez dans le travail d'équipe" },
        { name: "Humoristique", hint: "Rendez-le drôle ou inattendu" },
      ],
      exampleAnswers: {
        Relationnel: "Leur conversation a servi de pont pour réparer leur amitié.",
        Professionnel: "Nous devons créer un pont entre les différents services.",
        Humoristique: "J'ai essayé de faire le pont, mais mon dos a dit non merci.",
      },
    },
    {
      id: "fr-3",
      targetWord: "flamme",
      contexts: [
        { name: "Romantique", hint: "Décrivez la passion ou l'amour" },
        { name: "Scientifique", hint: "Utilisez en chimie ou physique" },
        { name: "Professionnel", hint: "Utilisez métaphoriquement" },
      ],
      exampleAnswers: {
        Romantique: "C'était son ancienne flamme du lycée.",
        Scientifique: "Le test à la flamme a révélé la présence d'ions cuivre.",
        Professionnel: "Il faut attiser la flamme de l'innovation dans l'entreprise.",
      },
    },
    {
      id: "fr-4",
      targetWord: "courant",
      contexts: [
        { name: "Scientifique", hint: "Électricité ou océanographie" },
        { name: "Quotidien", hint: "Quelque chose d'habituel" },
        { name: "Humoristique", hint: "Jouez sur les sens multiples" },
      ],
      exampleAnswers: {
        Scientifique: "Le courant électrique a provoqué un court-circuit.",
        Quotidien: "C'est un problème courant dans cette région.",
        Humoristique: "Je suis au courant de tout, sauf de l'électricité chez moi.",
      },
    },
    {
      id: "fr-5",
      targetWord: "fleur",
      contexts: [
        { name: "Romantique", hint: "Décrivez la beauté ou l'amour" },
        { name: "Culinaire", hint: "Utilisez en cuisine" },
        { name: "Figuré", hint: "Expression idiomatique" },
      ],
      exampleAnswers: {
        Romantique: "Elle était la plus belle fleur de son jardin.",
        Culinaire: "Ajoutez une pincée de fleur de sel pour finir le plat.",
        Figuré: "Il était à fleur de peau ce matin-là.",
      },
    },
    {
      id: "fr-6",
      targetWord: "vague",
      contexts: [
        { name: "Maritime", hint: "Océan ou mer" },
        { name: "Abstrait", hint: "Quelque chose d'imprécis" },
        { name: "Tendance", hint: "Mouvement social" },
      ],
      exampleAnswers: {
        Maritime: "Une vague énorme a frappé le bateau.",
        Abstrait: "Sa réponse était trop vague pour être satisfaisante.",
        Tendance: "La vague écologique transforme notre société.",
      },
    },
    {
      id: "fr-7",
      targetWord: "note",
      contexts: [
        { name: "Musical", hint: "Son ou mélodie" },
        { name: "Scolaire", hint: "Évaluation" },
        { name: "Professionnel", hint: "Document ou mémo" },
      ],
      exampleAnswers: {
        Musical: "Elle a chanté cette note aiguë avec perfection.",
        Scolaire: "J'ai eu une bonne note à mon examen de maths.",
        Professionnel: "J'ai laissé une note sur ton bureau.",
      },
    },
    {
      id: "fr-8",
      targetWord: "clé",
      contexts: [
        { name: "Sécurité", hint: "Accès ou serrure" },
        { name: "Musical", hint: "Tonalité" },
        { name: "Solution", hint: "Élément essentiel" },
      ],
      exampleAnswers: {
        Sécurité: "J'ai perdu la clé de ma voiture.",
        Musical: "Ce morceau est en clé de sol.",
        Solution: "La communication est la clé du succès.",
      },
    },
    {
      id: "fr-9",
      targetWord: "racine",
      contexts: [
        { name: "Botanique", hint: "Plante" },
        { name: "Mathématique", hint: "Calcul" },
        { name: "Origine", hint: "Source ou fondation" },
      ],
      exampleAnswers: {
        Botanique: "Les racines de cet arbre sont impressionnantes.",
        Mathématique: "La racine carrée de 25 est 5.",
        Origine: "Il faut trouver la racine du problème.",
      },
    },
    {
      id: "fr-10",
      targetWord: "lumière",
      contexts: [
        { name: "Scientifique", hint: "Physique" },
        { name: "Figuré", hint: "Compréhension" },
        { name: "Artistique", hint: "Photographie ou art" },
      ],
      exampleAnswers: {
        Scientifique: "La lumière voyage à 300 000 km par seconde.",
        Figuré: "Son explication a fait la lumière sur le mystère.",
        Artistique: "La lumière du matin est parfaite pour les photos.",
      },
    },
  ],
  es: [
    {
      id: "es-1",
      targetWord: "chispa",
      contexts: [
        { name: "Romántico", hint: "Describe sentimientos o atracción" },
        { name: "Científico", hint: "Usa en contexto técnico/físico" },
        { name: "Profesional", hint: "Usa en contexto de negocios" },
      ],
      exampleAnswers: {
        Romántico: "Hubo una chispa instantánea entre ellos en la fiesta.",
        Científico: "La chispa generada por el electrodo encendió la mezcla de gas.",
        Profesional: "Su presentación encendió la chispa de la creatividad en el equipo.",
      },
    },
    {
      id: "es-2",
      targetWord: "puente",
      contexts: [
        { name: "Relacional", hint: "Describe conexión o reconciliación" },
        { name: "Profesional", hint: "Usa en trabajo en equipo" },
        { name: "Humorístico", hint: "Hazlo gracioso o inesperado" },
      ],
      exampleAnswers: {
        Relacional: "Su conversación sirvió de puente para reparar la amistad.",
        Profesional: "Necesitamos crear un puente entre los departamentos.",
        Humorístico: "Intenté hacer el puente en yoga, pero mi espalda dijo que no.",
      },
    },
    {
      id: "es-3",
      targetWord: "llama",
      contexts: [
        { name: "Romántico", hint: "Describe pasión o amor" },
        { name: "Científico", hint: "Usa en química o física" },
        { name: "Animal", hint: "El animal sudamericano" },
      ],
      exampleAnswers: {
        Romántico: "Ella era su antigua llama del instituto.",
        Científico: "El ensayo a la llama reveló la presencia de iones de cobre.",
        Animal: "Vimos una llama en el zoológico ayer.",
      },
    },
    {
      id: "es-4",
      targetWord: "corriente",
      contexts: [
        { name: "Científico", hint: "Electricidad u oceanografía" },
        { name: "Cotidiano", hint: "Algo habitual" },
        { name: "Humorístico", hint: "Juega con los múltiples significados" },
      ],
      exampleAnswers: {
        Científico: "La corriente eléctrica provocó un cortocircuito.",
        Cotidiano: "Es un problema corriente en esta zona.",
        Humorístico: "Estoy al corriente de todo, menos de la electricidad en mi casa.",
      },
    },
    {
      id: "es-5",
      targetWord: "flor",
      contexts: [
        { name: "Romántico", hint: "Describe belleza o amor" },
        { name: "Culinario", hint: "Usa en cocina" },
        { name: "Figurado", hint: "Expresión idiomática" },
      ],
      exampleAnswers: {
        Romántico: "Ella era la flor más bella de su jardín.",
        Culinario: "Añade una pizca de flor de sal para terminar el plato.",
        Figurado: "Llegó en la flor de la vida.",
      },
    },
    {
      id: "es-6",
      targetWord: "ola",
      contexts: [
        { name: "Marítimo", hint: "Océano o mar" },
        { name: "Tendencia", hint: "Movimiento social" },
        { name: "Saludo", hint: "Gesto social" },
      ],
      exampleAnswers: {
        Marítimo: "Una ola enorme golpeó el barco.",
        Tendencia: "La ola ecológica está transformando nuestra sociedad.",
        Saludo: "Le hizo una ola desde el otro lado de la calle.",
      },
    },
    {
      id: "es-7",
      targetWord: "nota",
      contexts: [
        { name: "Musical", hint: "Sonido o melodía" },
        { name: "Escolar", hint: "Evaluación" },
        { name: "Profesional", hint: "Documento o memo" },
      ],
      exampleAnswers: {
        Musical: "Cantó esa nota aguda con perfección.",
        Escolar: "Obtuve una buena nota en mi examen de matemáticas.",
        Profesional: "Dejé una nota en tu escritorio.",
      },
    },
    {
      id: "es-8",
      targetWord: "clave",
      contexts: [
        { name: "Seguridad", hint: "Acceso o contraseña" },
        { name: "Musical", hint: "Tonalidad" },
        { name: "Solución", hint: "Elemento esencial" },
      ],
      exampleAnswers: {
        Seguridad: "Olvidé la clave de mi cuenta de correo.",
        Musical: "Esta pieza está en clave de sol.",
        Solución: "La comunicación es clave para el éxito.",
      },
    },
    {
      id: "es-9",
      targetWord: "raíz",
      contexts: [
        { name: "Botánico", hint: "Planta" },
        { name: "Matemático", hint: "Cálculo" },
        { name: "Origen", hint: "Fuente o fundamento" },
      ],
      exampleAnswers: {
        Botánico: "Las raíces de este árbol son impresionantes.",
        Matemático: "La raíz cuadrada de 25 es 5.",
        Origen: "Hay que encontrar la raíz del problema.",
      },
    },
    {
      id: "es-10",
      targetWord: "luz",
      contexts: [
        { name: "Científico", hint: "Física" },
        { name: "Figurado", hint: "Comprensión" },
        { name: "Artístico", hint: "Fotografía o arte" },
      ],
      exampleAnswers: {
        Científico: "La luz viaja a 300.000 km por segundo.",
        Figurado: "Su explicación arrojó luz sobre el misterio.",
        Artístico: "La luz de la mañana es perfecta para las fotos.",
      },
    },
  ],
};
