// Exercise 1: Rapid Context Switch
export interface ContextSwitchChallenge {
  id: string;
  targetWord: string;
  contexts: { name: string; hint: string }[];
  exampleAnswers: Record<string, string>;
}

export const contextSwitchChallenges: ContextSwitchChallenge[] = [
  {
    id: "1",
    targetWord: "spark",
    contexts: [
      { name: "Romantic", hint: "Describe feelings or attraction" },
      { name: "Scientific", hint: "Use in a technical/physics context" },
      { name: "Professional", hint: "Use in a business/career context" },
    ],
    exampleAnswers: {
      Romantic: "There was an instant spark between them at the party.",
      Scientific: "The spark generated by the electrode ignited the gas mixture.",
      Professional: "Her presentation sparked a new direction for the project.",
    },
  },
  {
    id: "2",
    targetWord: "bridge",
    contexts: [
      { name: "Romantic", hint: "Describe connection or reconciliation" },
      { name: "Professional", hint: "Use in teamwork or networking" },
      { name: "Humorous", hint: "Make it funny or unexpected" },
    ],
    exampleAnswers: {
      Romantic: "Their late-night conversation bridged the gap that had grown between them.",
      Professional: "We need to bridge the communication gap between departments.",
      Humorous: "I tried to bridge the gap in my pants, but the button had other plans.",
    },
  },
  {
    id: "3",
    targetWord: "flame",
    contexts: [
      { name: "Romantic", hint: "Describe passion or love" },
      { name: "Scientific", hint: "Use in chemistry or physics" },
      { name: "Professional", hint: "Use metaphorically in business" },
    ],
    exampleAnswers: {
      Romantic: "She was his old flame from college, and seeing her reignited forgotten feelings.",
      Scientific: "The flame test revealed the presence of copper ions in the solution.",
      Professional: "We need to fan the flame of innovation in our team.",
    },
  },
  {
    id: "4",
    targetWord: "current",
    contexts: [
      { name: "Scientific", hint: "Use in electricity or oceanography" },
      { name: "Professional", hint: "Use about trends or status" },
      { name: "Humorous", hint: "Play with the word's multiple meanings" },
    ],
    exampleAnswers: {
      Scientific: "The ocean current carried the debris hundreds of miles from shore.",
      Professional: "Our current strategy isn't yielding the expected results.",
      Humorous: "I'm not current on the news because my electricity got cut off.",
    },
  },
  {
    id: "5",
    targetWord: "bloom",
    contexts: [
      { name: "Romantic", hint: "Describe love or beauty" },
      { name: "Scientific", hint: "Use in biology or ecology" },
      { name: "Professional", hint: "Use about growth or success" },
    ],
    exampleAnswers: {
      Romantic: "Their love bloomed slowly, like a flower opening to the sun.",
      Scientific: "The algal bloom in the lake depleted oxygen levels significantly.",
      Professional: "Her career really started to bloom after the promotion.",
    },
  },
];

// Exercise 2: Filler Word Eliminator
export const fillerWords = ["um", "uh", "like", "you know", "basically", "literally", "actually", "sort of", "kind of", "I mean"];

export const speakingTopics = [
  "Describe your ideal weekend",
  "Explain why you chose your current job or field of study",
  "Talk about a memorable trip you've taken",
  "Describe your morning routine",
  "Explain how to make your favorite meal",
  "Talk about a skill you'd like to learn",
  "Describe your favorite book or movie",
  "Explain why exercise is important",
  "Talk about a challenge you overcame",
  "Describe your dream home",
];

// Exercise 4: One-Minute Micro-Talks
export const microTalkTopics = [
  { topic: "The importance of sleep", category: "Health" },
  { topic: "Why hobbies matter", category: "Lifestyle" },
  { topic: "The future of remote work", category: "Business" },
  { topic: "Benefits of reading", category: "Education" },
  { topic: "Climate change solutions", category: "Environment" },
  { topic: "The value of failure", category: "Personal Growth" },
  { topic: "Technology in education", category: "Tech" },
  { topic: "Building good habits", category: "Self-improvement" },
  { topic: "The power of gratitude", category: "Mindfulness" },
  { topic: "Effective communication", category: "Skills" },
];

// Exercise 5: Reverse Definitions
export interface ReverseDefinition {
  id: string;
  definition: string;
  answer: string;
  hints: string[];
  difficulty: "easy" | "medium" | "hard";
}

export const reverseDefinitions: ReverseDefinition[] = [
  { id: "1", definition: "A feeling of great happiness and triumph", answer: "elation", hints: ["Starts with 'e'", "Has 7 letters"], difficulty: "medium" },
  { id: "2", definition: "Speaking or writing in a clear and effective way", answer: "articulate", hints: ["Starts with 'a'", "Can be verb or adjective"], difficulty: "medium" },
  { id: "3", definition: "A person who doubts or questions everything", answer: "skeptic", hints: ["Starts with 's'", "Greek origin"], difficulty: "easy" },
  { id: "4", definition: "Existing everywhere at the same time", answer: "ubiquitous", hints: ["Starts with 'u'", "Latin origin"], difficulty: "hard" },
  { id: "5", definition: "To make something seem less important than it is", answer: "understate", hints: ["Compound word", "Opposite of exaggerate"], difficulty: "easy" },
  { id: "6", definition: "A temporary state of mind or feeling", answer: "mood", hints: ["4 letters", "Very common word"], difficulty: "easy" },
  { id: "7", definition: "The ability to understand and share feelings of another", answer: "empathy", hints: ["Starts with 'e'", "Often confused with sympathy"], difficulty: "medium" },
  { id: "8", definition: "Extremely idealistic; unrealistic and impractical", answer: "quixotic", hints: ["From literature", "Starts with 'q'"], difficulty: "hard" },
  { id: "9", definition: "Brief and to the point", answer: "concise", hints: ["Starts with 'c'", "Opposite of verbose"], difficulty: "medium" },
  { id: "10", definition: "A strong feeling of dislike or disapproval", answer: "aversion", hints: ["Starts with 'a'", "Often paired with 'to'"], difficulty: "medium" },
];

// Exercise 6: Narrative Puzzle Builder
export interface NarrativeChallenge {
  id: string;
  requiredWords: string[];
  theme: string;
  minSentences: number;
}

export const narrativeChallenges: NarrativeChallenge[] = [
  { id: "1", requiredWords: ["midnight", "whisper", "ancient"], theme: "Mystery", minSentences: 3 },
  { id: "2", requiredWords: ["courage", "storm", "discovered"], theme: "Adventure", minSentences: 3 },
  { id: "3", requiredWords: ["laughter", "unexpected", "gift"], theme: "Heartwarming", minSentences: 3 },
  { id: "4", requiredWords: ["silence", "truth", "finally"], theme: "Drama", minSentences: 3 },
  { id: "5", requiredWords: ["brilliant", "mistake", "fortune"], theme: "Comedy", minSentences: 3 },
];

// Exercise 7: Tone Transformer
export interface ToneChallenge {
  id: string;
  neutralSentence: string;
  targetTones: string[];
  exampleTransformations: Record<string, string>;
}

export const toneChallenges: ToneChallenge[] = [
  {
    id: "1",
    neutralSentence: "The project deadline has been moved to next week.",
    targetTones: ["Formal", "Friendly", "Urgent"],
    exampleTransformations: {
      Formal: "Please be advised that the project deadline has been extended to the following week.",
      Friendly: "Great news! We've got an extra week to wrap up the project.",
      Urgent: "Attention: The deadline shift to next week means we need to adjust our timeline immediately.",
    },
  },
  {
    id: "2",
    neutralSentence: "I disagree with your opinion.",
    targetTones: ["Diplomatic", "Direct", "Humorous"],
    exampleTransformations: {
      Diplomatic: "I appreciate your perspective, though I see this matter somewhat differently.",
      Direct: "I have to be straight with you—I don't share that view.",
      Humorous: "If opinions were pizza toppings, we'd definitely be ordering from different menus!",
    },
  },
  {
    id: "3",
    neutralSentence: "The restaurant food was not good.",
    targetTones: ["Formal Review", "Casual", "Sarcastic"],
    exampleTransformations: {
      "Formal Review": "The culinary offerings failed to meet acceptable standards of quality.",
      Casual: "Honestly? The food was pretty disappointing.",
      Sarcastic: "Well, if you enjoy flavors reminiscent of cardboard, you'll love this place!",
    },
  },
  {
    id: "4",
    neutralSentence: "You need to improve your work.",
    targetTones: ["Encouraging", "Professional", "Direct"],
    exampleTransformations: {
      Encouraging: "I see so much potential in your work—let's explore ways to help it shine even brighter!",
      Professional: "There are specific areas in your deliverables that would benefit from enhancement.",
      Direct: "Your current output isn't meeting expectations. Let's fix that.",
    },
  },
];

// Exercise 8: Synonym Speed Chain
export interface SynonymChallenge {
  id: string;
  word: string;
  commonSynonyms: string[];
  rareSynonyms: string[];
  timeLimit: number;
}

export const synonymChallenges: SynonymChallenge[] = [
  { id: "1", word: "happy", commonSynonyms: ["joyful", "glad", "pleased", "content", "cheerful"], rareSynonyms: ["elated", "jubilant", "blissful", "ecstatic", "euphoric"], timeLimit: 30 },
  { id: "2", word: "sad", commonSynonyms: ["unhappy", "upset", "down", "gloomy", "sorrowful"], rareSynonyms: ["melancholy", "despondent", "forlorn", "disconsolate", "woebegone"], timeLimit: 30 },
  { id: "3", word: "big", commonSynonyms: ["large", "huge", "enormous", "giant", "massive"], rareSynonyms: ["colossal", "mammoth", "gargantuan", "immense", "titanic"], timeLimit: 30 },
  { id: "4", word: "smart", commonSynonyms: ["clever", "intelligent", "bright", "sharp", "quick"], rareSynonyms: ["astute", "sagacious", "perspicacious", "erudite", "shrewd"], timeLimit: 30 },
  { id: "5", word: "beautiful", commonSynonyms: ["pretty", "lovely", "gorgeous", "attractive", "stunning"], rareSynonyms: ["resplendent", "ravishing", "exquisite", "sublime", "pulchritudinous"], timeLimit: 30 },
];

// Exercise 9: Question Crafting Lab
export interface QuestionChallenge {
  id: string;
  statement: string;
  questionTypes: { type: string; example: string }[];
}

export const questionChallenges: QuestionChallenge[] = [
  {
    id: "1",
    statement: "The new policy will change how employees work.",
    questionTypes: [
      { type: "Clarifying", example: "In what specific ways will the new policy change employee workflows?" },
      { type: "Probing", example: "What considerations led to implementing this particular policy change?" },
      { type: "Open-ended", example: "How do you think employees will adapt to this new policy?" },
    ],
  },
  {
    id: "2",
    statement: "The project was successful.",
    questionTypes: [
      { type: "Clarifying", example: "What metrics were used to determine the project's success?" },
      { type: "Probing", example: "What factors contributed most significantly to this success?" },
      { type: "Open-ended", example: "How might this success influence future projects?" },
    ],
  },
  {
    id: "3",
    statement: "Technology is changing education.",
    questionTypes: [
      { type: "Clarifying", example: "Which specific technologies are having the biggest impact on education?" },
      { type: "Probing", example: "What challenges arise from integrating technology into traditional education?" },
      { type: "Open-ended", example: "How do you envision education evolving with technology in the next decade?" },
    ],
  },
];

// Exercise 10: Repair & Rephrase
export interface RepairChallenge {
  id: string;
  clunkySentence: string;
  issues: string[];
  improvedVersions: string[];
  explanation: string;
}

export const repairChallenges: RepairChallenge[] = [
  {
    id: "1",
    clunkySentence: "Due to the fact that it was raining, the game was cancelled.",
    issues: ["Wordy phrase 'due to the fact that'"],
    improvedVersions: ["Because it was raining, the game was cancelled.", "The game was cancelled due to rain."],
    explanation: "Replace 'due to the fact that' with simply 'because' for conciseness.",
  },
  {
    id: "2",
    clunkySentence: "He is a person who always tells the truth.",
    issues: ["Unnecessary 'person who' construction"],
    improvedVersions: ["He always tells the truth.", "He is honest."],
    explanation: "Remove filler phrases like 'is a person who' for more direct statements.",
  },
  {
    id: "3",
    clunkySentence: "At this point in time, we are currently experiencing difficulties.",
    issues: ["Redundant phrases", "Passive construction"],
    improvedVersions: ["We're having difficulties now.", "We're facing challenges."],
    explanation: "'At this point in time' and 'currently' are redundant. Be direct.",
  },
  {
    id: "4",
    clunkySentence: "The meeting that was scheduled for today has been postponed until tomorrow.",
    issues: ["Passive voice", "Wordiness"],
    improvedVersions: ["Today's meeting has been moved to tomorrow.", "We've postponed today's meeting to tomorrow."],
    explanation: "Remove unnecessary relative clauses and consider active voice.",
  },
  {
    id: "5",
    clunkySentence: "In my opinion, I think that the proposal is good.",
    issues: ["Redundancy: 'in my opinion' and 'I think'"],
    improvedVersions: ["I think the proposal is good.", "The proposal looks promising."],
    explanation: "'In my opinion' and 'I think' mean the same thing—use only one.",
  },
  {
    id: "6",
    clunkySentence: "She has the ability to play the piano very well.",
    issues: ["Wordy phrase 'has the ability to'"],
    improvedVersions: ["She plays the piano very well.", "She's an excellent pianist."],
    explanation: "Replace 'has the ability to' with a simple verb.",
  },
];
